### ISSUE TITLE
Update to Django 3.0

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#344]
In addition to testing our own code for Django 3.0 compatibility, some dependencies need to be updated. `django-crispy-bulma` in particular is currently blocking (and maybe `django-environ` - see notes below).

## Dependencies

| Name | Version in Master | 3.0 Compatible Version | Notes |
| ---- |:-----------------:|:----------------------:| ----- |
| django-allauth | 0.41.0 | 0.41.0 | |
| django-crispy-bulma | 0.2.0 | ❌ | It requires django-crispy-forms 1.7 but 1.8 is the minimum version with support for Django 3.0. |
| django-crispy-forms | 1.7.2 | **1.8.0** | |
| django-environ | 0.4.5 | ❌ ❔ | Still seems to work for our purposes, despite an issue being open requesting Django 3.0 support. |
| django-filter | 2.1.0 | 2.1.0 | |
| django-hosts | 3.0.0 | **4.0.0** | |
| django-simple-bulma | 1.2.0 | 1.2.0 | |
| djangorestframework | 3.9.4 | **3.11.0** | Need to deal with `base_name`, deprecated in encode/django-rest-framework#5990, finally being dropped completely. |
| djangorestframework-bulk | 0.2.1 | ❔ | Project is dead. |
| sentry-sdk | 0.14.2 | 0.14.0 | |
| whitenoise | 4.1.2 | **5.0.0** | |
| wiki | 0.5.0 | **0.6b1** | It is in beta so it needs to be a VCS dependency. |

## Tests

Some tests are failing:

```
======================================================================
FAIL: test_accepts_valid_data_and_sets_actor (pydis_site.apps.api.tests.test_deleted_messages.DeletedMessagesWithActorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mark/repos/python/site-pydis/pydis_site/apps/api/tests/test_deleted_messages.py", line 78, in test_accepts_valid_data_and_sets_actor
    self.assertEqual(response.status_code, 201)
AssertionError: 400 != 201

======================================================================
FAIL: test_accepts_valid_data (pydis_site.apps.api.tests.test_deleted_messages.DeletedMessagesWithoutActorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mark/repos/python/site-pydis/pydis_site/apps/api/tests/test_deleted_messages.py", line 45, in test_accepts_valid_data
    self.assertEqual(response.status_code, 201)
AssertionError: 400 != 201
```

**Comment by MarkKoz** [comment]
I think `django-environ` is only broken if trying to read an `.env`. We rely on `pipenv` to read the file instead so we should be fine.
